@startuml

title MongoDB Payments Model

interface BasePayment {
    + transactionId: ObjectId
    + orderId: ObjectId
    + amount: Value
    + notes: Note[]
}

class Transaction {
    - receiver: BaseClient
    - sender: User
    - transactionLink: string
    - receipt: string
    - timestamp: Date
    + get(): Transaction
    + set(transaction: Transaction)
}

class Payment extends BasePayment {
    - confirmed: boolean
    + get(): Payment
    + set(confirmed: boolean)
}

' Inherit (interfaces)
BasePayment <|.. Payment

' Composition
BasePayment *--> Transaction
BasePayment *--> Value

' Notes
note top of Transaction
Sender must be an user of the app,
which, in theory, has the "Stripe"
or "Mercado Pago" module activated
endnote

note top of Payment
The payment class represents the
final form of a payment
endnote

@enduml