@startuml

title MongoDB PaymentMethods Model

interface BasePaymentMethods {
    + name: Name
    + accountOwners: User[]
    + accountNumber: string
    + get()
    + set(data: BasePaymentMethods)
}

class PaymentMethod {

}

' Inheritance (interface)

BasePaymentMethods <|.. PaymentMethod