@startuml

interface BaseSales {
    + seller: User
    + buyer: Client
    + payment: Payment
}

class Sale {

}

' Inheritance
BaseSales <|.r. Sales

' Composition
BaseSales *--> User
BaseSales *--> Client
BaseSales *--> Payment

@enduml