@startuml

title MongoDB User Model

interface BaseClient {
    - _id: ObjectId
    - type: string
    + name: Name
    + phone: Phone
    + email: Email
    + thumbnail: Thumbnail
    + notes: Note[]
    + getId()
    + getType()
    + setId()
    + setType(type: string)
}

' interface BaseUser extends BaseClient
interface BaseUser {
    + password: Password
    + role: Role
}

' class Client implements BaseClient
class Client {

}

' class User implements BaseUser
class User {
    + registerUserCookies(c: Context): boolean
    + save(this): User
    + registerUser(): User
    + signUser(): string
}

' class Supplier implements BaseClient
class Supplier {
    + webpage: Link
    + description: Description
}

' :: TINY OBJECTS ::

class Password {
    - password: string
    - encrypt(password: string): Promise<string>
    + set(password: string)
    + validate(password: string): Promise<string>
}

class Role {
    - role: Map<string, number>
    + get()
    + getOne(name)
    + set(role: Map<string, number>)
    + add(role: Map<string, number>)
}

class Name {
    - names: string[]
    - alias: string
    + get(): string
    + getOne(i): string
    + getAlias(): string
    + set(fullName): string
    + add(name): string
    + setAlias(alias): string
}

class Phone {
    - country: string
    - number: string
    - validate(phone: Phone): boolean
    + get()
    + set(phone: Phone)
}

class Email {
    - email
    - validate(email: Email)
    + get()
    + set(email: Email)
}

class Description {
    - body: string
    - timestamp: Date
    - validate(description: Description): boolean
    + get()
    + set(description: Description)
}

class Thumbnail {
    - link: string
    - timestamp: Date
    - validate(thumbnail: Thumbnail): boolean
    + get()
    + set(thumbnail: Thumbnail)
}

class Note {
    - tags: string
    - body: string
    - timestamp: Date
    - validate(email: Email)
    + get()
    + set(email: Email)
}

class Link {
    - link
    - validate(link: string): boolean
    + get()
    + set(link: string)
}

' Inherit (interfaces). For classes,
' remember: ClasePadre <|-- ClaseHija
BaseClient <|.r. BaseUser
BaseUser <|.. User
BaseClient <|.l. Supplier
BaseClient <|.l. Client

' Composition
BaseClient *--> Name
BaseClient *--> Phone
BaseClient *--> Email
BaseClient *--> Thumbnail
BaseClient *--> Note
Supplier *..> Link
Supplier *..> Description
BaseUser *--> Password
BaseUser *--> Role

' Notes
note top of BaseClient
"type" property will set if the document
is representing a User, Client, Supplier,
DeliveryUser, etc.
endnote

@enduml